### ISSUE TITLE
Replacing hoa/protocol causes phpstan to fail

### ISSUE THREAD

**Issue by nickfls** [lorisleiva/laravel-search-string#35]
I know, this is probably a `sanmai/hoa-protocol` issues, but this package requires hoa/protocol and replaces is with `sanmai/hoa-protocol`.

This causes my L8 project to fail phpstan analysis
```bash
./vendor/bin/phpstan analyse app tests --memory-limit=2G
````
with 
```php
PHP Fatal error:  Cannot declare class Hoa\Protocol\Wrapper, because the name is already in use in /home/vagrant/Codetocol/Source/Wrapper.php on line 44
Fatal error: Cannot declare class Hoa\Protocol\Wrapper, because the name is already in use in /home/vagrant/Code/gene/Source/Wrapper.php on line 44
```

is there a reason for replacement?

**Comment by lorisleiva** [comment]
Hi there 👋 

This was due to a conflict with the `resolve` method on Laravel to resolve abstracts from the container. See PR https://github.com/lorisleiva/laravel-search-string/pull/21.

The Hoa compiler has been a bit of a pain for that sort of thing. I'd like to move away from it at some point and replace it with [Parsica](https://github.com/parsica-php/parsica) if it can reproduce the same features.
